name: Pull Request
on: [pull_request]

jobs:
  check-app:
    name: Check App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.2

      - uses: actions/setup-node@v4
        with:
          node-version: 24.20.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check lint
        run: pnpm lint

      - name: Check imports
        run: pnpm check-imports

      - name: Check types
        run: pnpm check-types

      - name: Build app
        run: pnpm build
